"""Aggregate the tau-bench learned-routing replicates into one paper table.

Reads the main run (taubench_routing_results.json) plus the rep2..rep5 replicate JSONs
(independent reruns of ONLY the two learned routers over the same 80 retail tasks, produced
by run_taubench_replicates.sh) and writes paper/figures/taubench_replicates_table.tex with
per-replicate success/cost and the across-replicate mean +/- s.d.

Run:  python examples/agentic/combine_taubench_replicates.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

FIGDIR = Path(__file__).resolve().parents[2] / "paper" / "figures"
REG, FLAT = "routed-regional (ours)", "routed-flat"


def main() -> None:
    files = [FIGDIR / "taubench_routing_results.json"] + [
        FIGDIR / f"taubench_routing_rep{i}_results.json" for i in range(2, 6)
    ]
    rows, reg_s, flat_s = [], [], []
    for i, f in enumerate(files, 1):
        if not f.exists():
            print(f"missing {f}")
            continue
        r = json.loads(f.read_text())["results"]
        rs, fs = r[REG]["success"], r[FLAT]["success"]
        rc, fc = r[REG]["cost"], r[FLAT]["cost"]
        reg_s.append(rs)
        flat_s.append(fs)
        rows.append(f"{i} & {rs:.3f} & {rc:.4f} & {fs:.3f} & {fc:.4f} \\\\")
    reg, flat = np.array(reg_s), np.array(flat_s)
    gap = reg - flat
    summary = (
        f"mean $\\pm$ s.d. & {reg.mean():.3f} $\\pm$ {reg.std(ddof=1):.3f} & & "
        f"{flat.mean():.3f} $\\pm$ {flat.std(ddof=1):.3f} & \\\\"
    )
    tex = (
        "% tau-bench replicate study (auto-generated by combine_taubench_replicates.py).\n"
        "% 5 independent replicates of the two learned routers, same 80 retail tasks.\n"
        "\\begin{tabular}{lcccc}\n\\toprule\n"
        " & \\multicolumn{2}{c}{regional (ours)} & \\multicolumn{2}{c}{flat} \\\\\n"
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\n"
        "Replicate & success & \\$/task & success & \\$/task \\\\\n\\midrule\n"
        + "\n".join(rows)
        + "\n\\midrule\n"
        + summary
        + "\n\\bottomrule\n\\end{tabular}\n"
    )
    (FIGDIR / "taubench_replicates_table.tex").write_text(tex)
    print(
        f"{len(reg_s)} replicates: regional {reg.mean():.3f}+/-{reg.std(ddof=1):.3f}, "
        f"flat {flat.mean():.3f}+/-{flat.std(ddof=1):.3f}, gap {gap.mean():+.3f}"
        f"+/-{gap.std(ddof=1):.3f}, regional ahead in {(gap > 0).sum()}/{len(reg_s)}"
    )
    print(f"wrote {FIGDIR / 'taubench_replicates_table.tex'}")


if __name__ == "__main__":
    main()
